### ISSUE TITLE
Label for 3rd Text Field Unreadable On OS X

### ISSUE THREAD

**Issue by mr-feek** [matt57225/bovada-hand-history-converter#2]
![image](https://user-images.githubusercontent.com/5747667/34472736-5b668464-ef36-11e7-8a3c-6b8cc940193a.png)

**Comment by matt57225** [comment]
Hello. I am no longer working on this converter but the  label is for the move folder.  If you select a folder there it will move original/input files to that folder after conversion.

**Comment by matt57225** [comment]
I'm sorry I mean will move original files there after conversion.

**Comment by matt57225** [comment]
Decided to work on this a bit and also upgrade it to Python 3. I increased the window size a bit.  No idea if that will fix this issue.  Let me know.

**Comment by matt57225** [comment]
Going to close this for now, if not working please let me know and will re-open it.
