### ISSUE TITLE
Pot size error when folded to the big blind preflop.

### ISSUE THREAD

**Issue by joshshifman** [matt57225/bovada-hand-history-converter#4]
So I'm getting lots of errors when importing into PT4 and they are due to the pot size being wrong. 

![screen shot 2018-04-09 at 9 22 41 pm](https://user-images.githubusercontent.com/4500158/38531074-32482ed6-3c3c-11e8-9aff-7810a55542c8.png)

They all seem to be in spots where it is folded to the big blind preflop and they collect the blinds. Here is an example of an Ignition HH and the corresponding (incorrect) Pokerstars HH.

>Ignition Hand #3589791199  Zone Poker ID#1232 HOLDEMZonePoker No Limit - 2018-04-07 13:54:40
Seat 1: UTG+1 ($19.58 in chips)
Seat 2: UTG+2 [ME] ($49.50 in chips)
Seat 3: Dealer ($58.62 in chips)
Seat 4: Small Blind ($9.91 in chips)
Seat 5: Big Blind ($60.27 in chips)
Seat 6: UTG ($47.42 in chips)
Dealer : Set dealer [3] 
Small Blind : Small Blind $0.25 
Big Blind : Big blind $0.50 
*** HOLE CARDS ***
UTG+1 : Card dealt to a spot [Ks 4c] 
UTG+2  [ME] : Card dealt to a spot [5c 9d] 
Dealer : Card dealt to a spot [6h 9h] 
Small Blind : Card dealt to a spot [9c 2h] 
Big Blind : Card dealt to a spot [5h Td] 
UTG : Card dealt to a spot [6s 3c] 
Big Blind : Leave(Auto)
UTG+2  [ME] : Leave(Auto)
UTG+1 : Leave(Auto)
Dealer : Leave(Auto)
UTG : Folds
UTG : Leave(Auto)
UTG+1 : Folds
UTG+2  [ME] : Folds
Dealer : Folds
Small Blind : Folds
Small Blind : Leave(Auto)
Big Blind : Showdown(High Card)
Big Blind : Hand result $0.75 
Enter(Auto)
Enter(Auto)
Enter(Auto)
Dealer : Enter(Auto)
Enter(Auto)
Enter(Auto)
*** SUMMARY ***
Total Pot($0.75)
Seat+1: UTG+1 lost with High Card [Ks 4c]  
Seat+2: UTG+2 lost with High Card [5c 9d]  
Seat+3: Dealer lost with High Card [6h 9h]  
Seat+4: Small Blind Folded before the RIVER
Seat+5: Big Blind $0.75  with High Card [5h Td]  
Seat+6: UTG Folded before the RIVER

>PokerStars Zoom Hand #3589791199:  Hold'em No Limit ($0.25/$0.50) - 2018/04/07 13:54:40 ET
Table 'Zone Poker ID 1232 6-max' 6-max Seat #3 is the button
Seat 1: UTG+1 ($19.58 in chips) 
Seat 2: Hero ($49.50 in chips) 
Seat 3: Dealer ($58.62 in chips) 
Seat 4: Small Blind ($9.91 in chips) 
Seat 5: Big Blind ($60.27 in chips) 
Seat 6: UTG ($47.42 in chips) 
Small Blind: posts small blind $0.25
Big Blind: posts big blind $0.50
*** HOLE CARDS ***
Dealt to Hero [5c 9d]
UTG: folds 
UTG+1: folds 
Hero: folds 
Dealer: folds 
Small Blind: folds 
*** SHOW DOWN ***
Hero: shows [5c 9d] (a hand...)
Dealer: shows [6h 9h] (a hand...)
UTG: shows [6s 3c] (a hand...)
UTG+1: shows [Ks 4c] (a hand...)
Big Blind: shows [5h Td] (a hand...)
Small Blind: shows [9c 2h] (a hand...)
Uncalled bet ($0) returned to Big Blind
Big Blind collected $0.75 from pot
*** SUMMARY ***
Total pot $0.75 | Rake $0.00
Seat 1: UTG+1 folded
Seat 2: Hero folded
Seat 3: Dealer folded
Seat 4: Small Blind folded
Seat 5: Big Blind collected ($0.50)
Seat 6: UTG folded

**Comment by matt57225** [comment]
Thank you for the feedback.  I made a change and I think it fixed the issue (tested the hand history you gave here and it imported).  Let me know if not working for you.

**Comment by joshshifman** [comment]
It is working now. Thanks!
