### ISSUE TITLE
Hands only convert to PokerStars

### ISSUE THREAD

**Issue by e-mal** [matt57225/bovada-hand-history-converter#8]
Hey Matt, 

I was wondering if you've looked at how to get the hands to import as a Bovada/Ignition hand after formatting it like a PokerStars hand. I want to be able to view hands imported under the same hero on the same iPoker site. Do you know if this is possible?

Thanks!

**Comment by matt57225** [comment]
Hi. I don't understand what you are trying to do. Are you using hm2 or pt4?

**Comment by matt57225** [comment]
Its been a while so hopefully you got what you were trying to do working.  If not please open a new issue and let me know because I don't understand based on your original description what you were trying to do.
